#! /usr/bin/env python
import sys
sys.path.append('./src/')

import statistical
from optparse import OptionParser 
import unittest

VERSION_FILE = 'VERSION.txt'

def main():
	"""Main entry method to the Kyffin project."""
	(options, args) = parse()

	if options.test_flag:
		from test.statistical_test import StatisticalTest
		suite = unittest.TestLoader().loadTestsFromTestCase(StatisticalTest)
		unittest.TextTestRunner(verbosity=2).run(suite)
	else :
		print "Kyffin ({0})".format(loadVersion())

def parse():
	parser = OptionParser()
	parser.add_option('-t', '--test', default=False, action='store_true', dest='test_flag', help='Run tests and nothing else')
	return parser.parse_args()

def loadVersion():
	"""Loads Version information from the file defined by VERSION_FILE"""
	version = 'Unkown Version'
	try:
		with open(VERSION_FILE, 'r') as vFile:
			version = vFile.readline().rstrip('\n')
	except IOError as e:
		print "Unable to load version file: {0}\nReason: {1}".format(VERSION_FILE, e)
	return version
	

if __name__ == '__main__':
	main();
else:
	print 'Needs to be run as an entry point.'
