#! /usr/bin/env python
import sys

# Use local imports relative to ./src/ for convinience
sys.path.append('./src/')

import analysis.analyserFactory as analyserFactory
import gui.guiFactory as guiFactory

from analyser import Analyser
from optparse import OptionParser 
import unittest

VERSION_FILE = 'VERSION.txt'

def main():
	"""Main entry method to the Kyffin project."""
	(options, args) = parse()

	if options.test_flag:
		from test.statistical_test import StatisticalTest
		suite = unittest.TestLoader().loadTestsFromTestCase(StatisticalTest)
		unittest.TextTestRunner(verbosity=2).run(suite)
	else :
		print "Kyffin ({0})".format(loadVersion())
		if options.csv is not None:
			analyser = Analyser(analyserFactory.getTechnique(options.analyser), guiFactory.getGUI(options.gui, options.analyser))
			analyser.run(options.csv)
		else:
			raise BaseException('No data file specified')

def parse():
	parser = OptionParser()
	parser.add_option('-t', '--test', default=False, action='store_true', dest='test_flag', help='Run tests and nothing else.')
	parser.add_option('-a', '--analyser', default='rgb', dest='analyser', help='Set Analyser type.')
	parser.add_option("-d", "--csv", dest="csv", help="Analyse CSV file.", metavar="CSV")
	parser.add_option('-g', '--gui', dest='gui', help='Set GUI type (defaults to text-based.')
	return parser.parse_args()

def loadVersion():
	"""Loads Version information from the file defined by VERSION_FILE"""
	version = 'Unkown Version'
	try:
		with open(VERSION_FILE, 'r') as vFile:
			version = vFile.readline().rstrip('\n')
	except IOError as e:
		print "Unable to load version file: {0}\nReason: {1}".format(VERSION_FILE, e)
	return version
	

if __name__ == '__main__':
	main();
else:
	print 'Needs to be run as an entry point.'
